### PR TITLE
Fix PHP 7.0 Support

### PR DESCRIPTION
**Pull request by erikn69**
https://github.com/php-zookeeper/php-zookeeper/pull/56#issuecomment-1438407155

### CODE REVIEW

**Comment by mlocati** [comment]
@erikn69 Yep, it seems to work!

I've tested it with my [install-php-extensions](https://github.com/mlocati/docker-php-extension-installer):

```
/ $ docker run --rm -it php:7.0-cli-alpine sh
/ # curl -sSL -o - \
    https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
    | sh -s https://codeload.github.com/php-zookeeper/php-zookeeper/tar.gz/25c6953e1be78516517c9540111807227ba873d5

[...omissis...]

/ # php --ri zookeeper

zookeeper

zookeeper support => enabled
version => 1.2.0
libzookeeper version => 3.7.1

Directive => Local Value => Master Value
zookeeper.recv_timeout => 10000 => 10000
zookeeper.session_lock => 1 => 1
zookeeper.sess_lock_wait => 150000 => 150000
```

**Comment by erikn69** [comment]
thanks for the feedback

**Comment by parallels999** [comment]
it works for me on 8.2 too, @Timandes  ping :)

**Comment by mlocati** [comment]
Are the TravisCI tests working?

**Comment by zhupeijie** [comment]
您好，邮件已收到，我近期会登录查看，祝您天天开心！

**Comment by Timandes** [comment]
```shell
# /opt/php-7.0-zts/bin/php -v
PHP 7.0.33 (cli) (built: Feb 21 2023 10:01:11) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```


```
=====================================================================
TIME END 2023-03-09 01:04:28

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   26
---------------------------------------------------------------------

Number of tests :  106                86
Tests skipped   :   20 ( 18.9%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   86 ( 81.1%) (100.0%)
---------------------------------------------------------------------
Time taken      :    8 seconds
=====================================================================
```

**Pull request merged**
