### PR TITLE
Add PHP 8.2 Support

### LINKED ISSUE #54: php 8.2 support
New php 8.2 is out, but zookeper extension doesn't support it.
Stack trace from [issue](https://github.com/mlocati/docker-php-extension-installer/issues/672)
```
#7 1503.6 2: /tmp/pickle.tmp/zookeeper/zookeeper-1.0.0/php_zookeeper.c: In function 'php_zk_watcher_marshal':
#7 1503.6 2: /tmp/pickle.tmp/zookeeper/zookeeper-1.0.0/php_zookeeper.c:1009:21: error: incompatible types when assigning to type 'zend_atomic_bool' {aka 'struct zend_atomic_bool_s'} from type 'int'
#7 1503.6 2:  1009 |  EG(vm_interrupt) = 1;
#7 1503.6 2:       |                     ^
#7 1503.6 2: /tmp/pickle.tmp/zookeeper/zookeeper-1.0.0/php_zookeeper.c: In function 'php_zk_completion_marshal':
#7 1503.6 2: /tmp/pickle.tmp/zookeeper/zookeeper-1.0.0/php_zookeeper.c:1053:21: error: incompatible types when assigning to type 'zend_atomic_bool' {aka 'struct zend_atomic_bool_s'} from type 'int'
#7 1503.6 2:  1053 |  EG(vm_interrupt) = 1;
#7 1503.6 2:       |                     ^
#7 1503.6 2: make: *** [Makefile:210: php_zookeeper.lo] Error 1
```

### PR DESCRIPTION
**Pull request by erikn69**
Closes #54
```
+ mkdir -p /tmp/php-zookeeper
+ cd /tmp/php-zookeeper
+ git clone https://github.com/erikn69/php-zookeeper.git .
Cloning into '.'...
+ git checkout patch-1
Switched to a new branch 'patch-1'
Branch 'patch-1' set up to track remote branch 'patch-1' from 'origin'.
+ phpize
Configuring for:
PHP Api Version:         20220829
Zend Module Api No:      20220829
Zend Extension Api No:   420220829
+ ./configure
+ make
/bin/bash /tmp/php-zookeeper/libtool --mode=compile cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper.c -o php_zookeeper.lo  -MMD -MF php_zookeeper.dep -MT php_zookeeper.lo
mkdir .libs
 cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper.c -MMD -MF php_zookeeper.dep -MT php_zookeeper.lo  -fPIC -DPIC -o .libs/php_zookeeper.o
/bin/bash /tmp/php-zookeeper/libtool --mode=compile cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/zoo_lock.c -o zoo_lock.lo  -MMD -MF zoo_lock.dep -MT zoo_lock.lo
 cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/zoo_lock.c -MMD -MF zoo_lock.dep -MT zoo_lock.lo  -fPIC -DPIC -o .libs/zoo_lock.o
/bin/bash /tmp/php-zookeeper/libtool --mode=compile cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_session.c -o php_zookeeper_session.lo  -MMD -MF php_zookeeper_session.dep -MT php_zookeeper_session.lo
 cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_session.c -MMD -MF php_zookeeper_session.dep -MT php_zookeeper_session.lo  -fPIC -DPIC -o .libs/php_zookeeper_session.o
/bin/bash /tmp/php-zookeeper/libtool --mode=compile cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_exceptions.c -o php_zookeeper_exceptions.lo  -MMD -MF php_zookeeper_exceptions.dep -MT php_zookeeper_exceptions.lo
 cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_exceptions.c -MMD -MF php_zookeeper_exceptions.dep -MT php_zookeeper_exceptions.lo  -fPIC -DPIC -o .libs/php_zookeeper_exceptions.o
/bin/bash /tmp/php-zookeeper/libtool --mode=compile cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_stat.c -o php_zookeeper_stat.lo  -MMD -MF php_zookeeper_stat.dep -MT php_zookeeper_stat.lo
 cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_stat.c -MMD -MF php_zookeeper_stat.dep -MT php_zookeeper_stat.lo  -fPIC -DPIC -o .libs/php_zookeeper_stat.o
/bin/bash /tmp/php-zookeeper/libtool --mode=compile cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_callback.c -o php_zookeeper_callback.lo  -MMD -MF php_zookeeper_callback.dep -MT php_zookeeper_callback.lo
 cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_callback.c -MMD -MF php_zookeeper_callback.dep -MT php_zookeeper_callback.lo  -fPIC -DPIC -o .libs/php_zookeeper_callback.o
/bin/bash /tmp/php-zookeeper/libtool --mode=compile cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_log.c -o php_zookeeper_log.lo  -MMD -MF php_zookeeper_log.dep -MT php_zookeeper_log.lo
 cc -I. -I/tmp/php-zookeeper -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -I/usr/local/include/php -DZEND_COMPILE_DL_EXT=1 -c /tmp/php-zookeeper/php_zookeeper_log.c -MMD -MF php_zookeeper_log.dep -MT php_zookeeper_log.lo  -fPIC -DPIC -o .libs/php_zookeeper_log.o
/bin/bash /tmp/php-zookeeper/libtool --mode=link cc -shared -I/tmp/php-zookeeper/include -I/tmp/php-zookeeper/main -I/tmp/php-zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE    -o zookeeper.la -export-dynamic -avoid-version -prefer-pic -module -rpath /tmp/php-zookeeper/modules  php_zookeeper.lo zoo_lock.lo php_zookeeper_session.lo php_zookeeper_exceptions.lo php_zookeeper_stat.lo php_zookeeper_callback.lo php_zookeeper_log.lo -lzookeeper_mt
cc -shared  .libs/php_zookeeper.o .libs/zoo_lock.o .libs/php_zookeeper_session.o .libs/php_zookeeper_exceptions.o .libs/php_zookeeper_stat.o .libs/php_zookeeper_callback.o .libs/php_zookeeper_log.o  -lzookeeper_mt  -Wl,-soname -Wl,zookeeper.so -o .libs/zookeeper.so
creating zookeeper.la
(cd .libs && rm -f zookeeper.la && ln -s ../zookeeper.la zookeeper.la)
/bin/bash /tmp/php-zookeeper/libtool --mode=install cp ./zookeeper.la /tmp/php-zookeeper/modules
cp ./.libs/zookeeper.so /tmp/php-zookeeper/modules/zookeeper.so
cp ./.libs/zookeeper.lai /tmp/php-zookeeper/modules/zookeeper.la
PATH="$PATH:/sbin" ldconfig -n /tmp/php-zookeeper/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /tmp/php-zookeeper/modules
```

### CODE REVIEW

**Comment by erikn69** [comment]
@Timandes please review

**Comment by mlocati** [comment]
Version 1.2.0 doesn't compile on PHP 7.0 (we should raise its mininum required version to 7.1, or fix support for PHP 7.0).

Here's the failure:

```
cc -I/usr/local/include/php -I. -I/tmp/pear/temp/zookeeper -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuser7AX7iJ/zookeeper-1.2.0/include -I/tmp/pear/temp/pear-build-defaultuser7AX7iJ/zookeeper-1.2.0/main -I/tmp/pear/temp/zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/zookeeper/php_zookeeper.c  -fPIC -DPIC -o .libs/php_zookeeper.o
 cc -I/usr/local/include/php -I. -I/tmp/pear/temp/zookeeper -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-defaultuser7AX7iJ/zookeeper-1.2.0/include -I/tmp/pear/temp/pear-build-defaultuser7AX7iJ/zookeeper-1.2.0/main -I/tmp/pear/temp/zookeeper -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/include/zookeeper -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/zookeeper/zoo_lock.c  -fPIC -DPIC -o .libs/zoo_lock.o
In file included from /usr/local/include/php/Zend/zend_globals.h:28:0,
                 from /usr/local/include/php/Zend/zend_compile.h:657,
                 from /usr/local/include/php/Zend/zend_modules.h:26,
                 from /usr/local/include/php/Zend/zend_API.h:27,
                 from /usr/local/include/php/main/php.h:39,
                 from /tmp/pear/temp/zookeeper/php_zookeeper.c:30:
/tmp/pear/temp/zookeeper/php_zookeeper.c: In function 'php_zk_watcher_marshal':
/usr/local/include/php/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals' has no member named 'vm_interrupt'
 # define EG(v) (executor_globals.v)
                                 ^
/tmp/pear/temp/zookeeper/php_zookeeper.c:1020:2: note: in expansion of macro 'EG'
  EG(vm_interrupt) = 1;
  ^
/tmp/pear/temp/zookeeper/php_zookeeper.c: In function 'php_zk_completion_marshal':
/usr/local/include/php/Zend/zend_globals_macros.h:46:33: error: 'zend_executor_globals' has no member named 'vm_interrupt'
 # define EG(v) (executor_globals.v)
                                 ^
/tmp/pear/temp/zookeeper/php_zookeeper.c:1071:2: note: in expansion of macro 'EG'
  EG(vm_interrupt) = 1;
  ^
```

([more details here](https://github.com/mlocati/docker-php-extension-installer/actions/runs/4232612170/jobs/7352572904))

**Comment by zhupeijie** [comment]
您好，邮件已收到，我近期会登录查看，祝您天天开心！

**Comment by parallels999** [comment]
@mlocati feel free to make a PR to fix that, thanks

**Comment by mlocati** [comment]
@parallels999 my knowledge of PHP internals is rather limited

**Comment by parallels999** [comment]
@mlocati use previous versions, example [php-fpm/Dockerfile#L1135-L1158](https://github.com/laradock/laradock/blob/6c8cb6dd85eb1fcad6f7dce3e9d6c6a29c6e3ed8/php-fpm/Dockerfile#L1135-L1158), or upgrade your php version

**Comment by erikn69** [comment]
@mlocati hi, i am not using PHP 7.0, could you test https://github.com/php-zookeeper/php-zookeeper/pull/57?
If it works for you, please let a review

**Pull request merged**
